/*CREAR BASE DE DATOS*/

DROP DATABASE IF EXISTS bd; --bd es el nombre de nuestra BBDD
CREATE DATABASE bd; 

USE bd;

CREATE TABLE PARTIDES (
	ID INT NOT NULL,
    DURACION INT,
    NUM_JUGADORES INT NOT NULL,
    PRIMARY KEY (ID)
) ENGINE= InnoDB;

CREATE TABLE JUGADOR (
	ID VARCHAR(),
    PUNTUACION INT,
    ID_PARTIDA INT NOT NULL,
    NUM_PROPIETATS INT(),
    DINERS INT,
    PRIMARY KEY (ID)
    FOREIGN KEY ID_PARTIDA REFERENCES PARTIDES (ID)
) ENGINE= InnoDB;


/*INSERTAR DATOS*/

INSERT INTO PARTIDES VALUES (1,100,2);
INSERT INTO PARTIDES VALUES (2,54,4);

INSERT INTO JUGADOR VALUES ('jordi_tort', 100, 1, 9, 525);
INSERT INTO JUGADOR VALUES ('ivan.gragera09', 187, 2, 12, 200);

